codedex-io/github-chapter-2-contributions

README.md
This is the last exercise from the Git & Github tutorial.
=> Final Exercise PR - magrumarian

README.md
Codédex account: https://www.codedex.io/@Vulpes
Added my name and todays date to the README.md file
=> Final Exercise PR - Vulpes

README.md
**Read this:** READ_ME file changed.
=> new changes on file

README.md
Remember to place the double space at the end of the line so that each name is on a different line or use <br>
=> Final Exercise PR - IngNicoRivas

README.md
Thank you for this exercise!!! ❤️
=> Final Exercise PR - harLekin

README.md
=> Final Exercise PR - Astrxnomo

README.md
=> Final Exercise PR - Limbert

README.md
Final Exercise PR - [username-here](https://www.codedex.io/@j1zuz)
=>  "Final Exercise PR - j1zuz"

README.md
=> Final Exercise PR - @DAVIELERM

README.md
=> Final Exercise PR - Max

README.md
Finished the final exercise (PR) eheh 😄
=> Final Exercise PR - aqu4riu-S

README.md
=> Final Exercise PR - ongThien

README.md
=> Final Exercise PR - eduhumanes91

README.md
Hi, my name is Musa! This was added on 19-03-2024 🧸
=> Final Exercise PR - uaaue

README.md
=> Final Exercise PR - KvRae

README.md
=> Final Exercise PR - Kashemanon here

README.md
=> Final Exercise PR - andymedina1

README.md
=> Final Exercise PR - Kelvis98

README.md
=> Final Exercise PR - Ani Dashyan

README.md
I added a self-introduction to the _README.md_ file
=> Final Exercise PR - canhphhust

README.md
=> Final Exercise PR - mariosplaton123

README.md
=> Final Exercise PR - Deepistertalks 

README.md
=> Added my line :)

README.md
=> Final Exercise PR - lumoski

README.md
=> Final Exercise PR - skhadraoui16

README.md
Added my line for the final github excercise
=> Final Exercise PR - m4xy07

README.md
YAY finally got my commit with eric!
=> added my name with emoji

README.md
=> Final Exercise PR - babybhavani-here

README.md
Here is my addition for the github course
=> My addition to the exercice

README.md
I added my name and the date with a duck emoji! #quackers
=> Final Exercise PR hmkuklinski

README.md
I have done the following task with the main repository
1. Fork the repository
2. Clone the repository
3. Add your commit
4. Push to your repository
5. Create a pull request
=> Final Exercise PR - KunalParkhade

README.md
Practice forking, cloning, and creating a pull request
Added my name, date, and emoji :)
=> Final Exercise PR - GitHub: tamkaize / Codedex: bigchicken

README.md
added my name and current date to finish the first part of the git & github tutorial
=> Final Exercise PR - Smasheed

README.md
=> Final Exercise PR - Bruce-Lutaj

README.md
Fixes the order of a few previous commits and merges.
=> Update order of names in README.md

README.md
Added my name, date, and some emojis in the Readme as per the exercise.
=> Added my details in the Readme exercise

README.md
This is for part 12 of the Codédex Git course!
=> Final Exercise PR - andreshungbz

README.md
finishing the git section I've had a blast with it and learned a lot!
=> Final Exercise PR - BlueCollargiant

README.md
=> Final Exercise PR - username-namratajith my name

README.md
Added the line:
Hi, my name is David! This was added on 08/06/2024 🙈🙉🙊
=> I place my self on it :D

README.md
Git & Github Codedex Final Exercise - "Yearbook" submission by alexgaaranes (Alex Aranes)
=> Final Exercise PR - Alex Aranes

README.md
=> Final Exercise PR - tradaokamsa

README.md
=> Added my name to file

README.md
=> adding a message

README.md
Sweet and short lessons! They were very useful, thank you!
=> Final Exercise PR - minttyy89

README.md
=> Final Exercise PR - ishahzebali

README.md
=> Final PRs lesson! - Aaliyah Le

README.md
I added my name into the README file 😁
=> Final Exercise PR - banhmipan

README.md
Added my introduction in readme file 😊.
=> Final Exercise PR - RajeevRanjan5642

README.md
=> Final Exercise PR - ryancamargo

README.md
Making my pull request and greetings.
=> add carlosfcpinheiro greetings

README.md
=> Final Exercise PR - TechVoyager01

README.md
=> Final Exercise PR - s0n0f4L1ch

README.md
Add a line containing my name and the date to the README to finish the Codedex Github chapter
=> Final Exercise PR - SpencerS04

README.md
Added my name, date, and emoji
to the wall for the final Git & Github exercise!
=> Final Exercise PR - VixenCoder

README.md
=> Final Exercise PR - hgx

README.md
Updated README.md with required text
=> Final Exercise PR - swapneilbasutkar

README.md
I add my line with name date and emoji =)
=> Final Exercise PR  @xxiicode 

README.md
Adding my name to the final git exercise
=> Final Exercise PR - nickaldwin

README.md
YOOOO hello Codedex Lova you all!
=> Final Exercise PR - Adel13377

README.md
=> Final Exercise PR - owljackob

README.md
Adding my contribution to the readme file for the Codedex Github expansion!
=> Final Exercise PR - mamashell

README.md
=> Final Exercise PR - Shiro7w7r

README.md
My contribution for the final exercise of Chapter 2.
=> Final Exercise PR - sarahmckee714

README.md
Hi there team, this is my PR for the last project ✌️
=> Final Exercise PR - chinyiskan.

README.md
Seeing the `DD-MM-YYYY` requirement was nice as a non-American. 🤭
=> Final Exercise PR - M3R14M

README.md
My initial commit to the Codedex repository on Github
=>  Final Exercise PR - Jaskaran Singh

README.md
=> Final Exercise PR - DanieljVargas

README.md
added my name & date to the readme
=> Final Exercise PR - @meghansm

README.md
This course was super easy and helpful, thank you!
=> Final Exercise PR - Blossom-Painter (@blossompai54468)

README.md
=> Final Exercise PR - specterette

README.md
Adding a new register to the GitHub README.md file.
=> Final Exercise PR - ncescuderor

README.md
=> Final Exercise PR - pabloverduzco

README.md
=> Final Exercise PR - andrewdgore135093

README.md
=> thisischris

README.md
=> Final Exercise PR - goncalohgs

README.md
=> Final Exercise PR - RomanitoX

README.md
=> added new line to the fam

README.md
Thx for the great GIT Hub course <3 
although it kept me up all night xD
=> Final Exercise PR - Sherlokk

README.md
=> Add introduction for Nitai Satapathy

README.md
=> Noahs Commit

README.md
Final Exercise PR - abolfazlkh18469
=> Final Exercise PR - abolfazlkh18469

README.md
added my entry at the end of the file README.md
=> Final PR exercise maksliudva - here!

README.md
Adding a new contributor identity to this readme file
=> Final PR Exercise -krisprogra69597

README.md
There was some sentences that were missing emojis, so I added them
Closes #284
=> feat: add missing emojis to sentences that do not have them

README.md
It was a useful website practice Git thanks
=> Final Exercise PR - Titus Thomas

README.md
I've added my contribution! Thank you team! for providing this wonderful course!
=> Final Exercise PR - plusero

README.md
This course is great, this type of learning is amazing and doesn't bore you until you give up. Thanks for the amazing work.
=> Final Exercise PR - ElsProjects here

README.md
Final Exercise PR - MarceJua :)
=> Final Exercise PR - MarceJua

README.md
=> New changes made

README.md
=> Final Exercise PR - rcuthbertson25

README.md
Final Exercise PR - yrdaman Mention I'm **YRDAMAN** also here and made to End !!!!!!!
=> Updated README.md with my introduction and date

README.md
=> Final Exercise PR - chchjii

README.md
=> git hub corse completion 

README.md
Added my name to the README file.
=> Final Exercise PR - jguapp-here

README.md
Final Excercise PR - Charly2004
=> Final Excercise PR - Charly2004

README.md
=> Final Exercise PR - dood-coder

README.md
=> Final Exercise PR - Okte

README.md
added my name line to the yearbook
=> Final Exercise PR - cainebenoy

README.md
Final Exercise PR - rohitgarwad
=> Final Exercise PR - rohitgarwad

README.md
Changed the README file according the the instructions by adding name at end - Maya :)
=> Final Exercise PR - mehad18

README.md
Adding my own sing to the yearbook :)
=> adding my commit in yearbook

README.md
=> Added my name to the contribution file

README.md
=> Hello there, here is my contribution

README.md
Agregando nombre y fecha del ejercicio.
=> Final Exercise PR - @AlonPower

README.md
Adding my name to the Readme file
Thanks!
Luna : 22-02-2025
=> Final Exercise PR - Luna1120

README.md
myself Gokul and it was nice learning here!
=> Gokul name added

README.md
=> Final Exercise PR - H38-here

README.md
This course was very helpful and easy to follow. Thank you all for your amazing work! :smile:
=> Final Exercise PR - morenn06

README.md
=> add contribution

README.md
=> Here's my contribution!

README.md
added myself in the readme file :)
=> Final Exercise PR - pixeljellyfish

README.md
=> Final Exercise PR - meeksha

README.md
=> Final Exercise PR - nessquikcodes

README.md
No need to wait any longer. I've finally arrived.
=> Final Exercise PR - 706245-hash

README.md
=> Final Exercise PR - VroDukh

README.md
=> Final Exercise PR - rnz007

README.md
=> Final Exercise PR -bluexlina

README.md
Final Exercise PR - passosdarezzo
=> Final Exercise PR - passosdarezzo

README.md
=> Final Exercise PR - SoulThy

README.md
Hi, this is my assignment for the codedex
=> Final Exercise PR - ARhero

README.md
Signed on line 726 in the README.md file.
I've added this line: 
```
Hi, my name is nicookie! This was added on 03-04-2025 🐈‍⬛
```
=> Final Exercise PR - nicookie

README.md
=> Update 4/6/25 README.md

README.md
Hello my name is subert Williams and I put my name here :D
=> I have finished the chapter.

README.md
This is Mulla final exercice PR. thankyou codedex now i understand using git/github
=> Final Exercise PR - MullaSh

README.md
adding my name to the readme file
=> Final Exercise PR - evgeny94

README.md
i''ve done adding myself and finish git chapter
=> add me -winterest

README.md
This is my final exercise PR :)
=> Final Exercise PR - whereismytakoyaki (Imspk)

README.md
=> Final Exercise PR - Karl-Sue

README.md
Hi, my name is Eliú! This was added on 15/04/2025 🔥🔥🔥
=> Final Exercise PR - eliujs

README.md
Hello, nice to meet everyone here. Creating this pull request while learning with codedex is fun ! Feel free to connect 😄
=> Final Exercise PR - waijian1

README.md
=> Hello, I learn github

README.md
Update README to complete final exercise.
=> Final Exercise PR - jcobeadev

README.md
=> Final Exercise PR - Ellesar

README.md
Just added GitHub username and date
=> Message added

README.md
=> Final Exercise PR - Tony

README.md
=> Final Exercise PR - srdny

README.md
I added the sentence and updated the README file.
=> Final exercise

README.md
Final Exercise PR - Prk007
My GitHub name is CrackersUnbust.
My Name is Pratheesh Kumar
User Name in Codex is Prk007
=> Final Exercise PR - Prk007

README.md
Hi, this is my PR, I'm in codedex like Coenh. Thank you!
=> Final Exercise PR - Coenh95

README.md
=> Final Exercise PR - Akamugin

README.md
I added 805 and 806 lines as per the instructions
=> Final Exercise PR - Chandu291206

README.md
Final Exercise PR - VassiAeLin
=> Final Exercise PR - VassiAeLin

README.md
=> Final Exercise PR - 27betseyquigley

README.md
"Final Exercise PR - satvik-git-work"
=> added my name, date and an emoji to the README.md file as a part of the instruction

README.md
I have added my name and date to the bottom of the page.
=> Final Exercise PR - D-Woolfer

README.md
=> Final Exercise PR - randerson112

README.md
Finished adding my name on yearbook :D
=> Final Exercise PR - swanjwich

README.md
=> Final Exercise PR - nahsor-here

README.md
Added an intro line to the README with my name, date, and emoji.
=> Final Exercise PR - nikpiao-dev

README.md
=> Final Exercise PR - MargheritaZanchini

README.md
=> Final Exercise PR - qauzal

README.md
Adding a new line for Hazzadimp dated 15-05-2025.
=> Final Exercise PR - Hazzadimp

README.md
i have finally done committing to the Yearbook
=> rajnarayanan28 has done commit

README.md
=> Final Exercise PR - ANS929

README.md
=> Final Exercise PR - conghuan0502

README.md
Hello! Please review this and let me know! Thanks.
=> "Final Exercise PR - AnjanaJK

README.md
=> Final Exercise PR - xkm79

README.md
Final Exercise - PR - 1 line added
=> Final Exercise PR - Mattoroid

README.md
=> Final Exercise PR - dinhducbo2005 aka BabiBoo

README.md
Love Codedex for now. keep it up team :>
=> Final Exercise PR - OmarAwashreh

README.md
=> Final Exercise PR - eduant2607

README.md
Thank you for this course, this really helped me out for learning Git and GitHub. Im new in this field so this was fun completing it.
=> Final Exercise PR - PepoSG

README.md
I Add my nickname, date and emoji on file
=> Changes on README.md

README.md
Final Exercise PR - HumbleCoder (Codex)
=> Final Exercise PR - HumbleCoder

README.md
I have updated the README.md file as required for this exercise.
=> Final Exercise PR - Dom0017

README.md
Thanks for the tutorials it helps a lot! namaste...🙏
=> Final Exercise PR - Rizzverano

README.md
=> Final Exercise PR - ArmandoN22

README.md
=> Final Exercise PR - fernandoirangph

README.md
Added name and date to contributions file
=> Final Exercise PR - hasanardaaydogan

README.md
=> Final Exercise PR - kelly990918

README.md
Final Exercise PR -  xiaofanwindy
=> Final Exercise PR -  xiaofanwindy

README.md
You're doing a good job, let's keep going!
=> Final Exercise PR - madesh-arul

README.md
I added my greeting with emojis 😄
=> Final Exercise PR -  @RussTP

README.md
Logged my contribution,
xoxo
Ak
=> Final Exercise PR - Akshaya-Thummala

README.md
=> Final Exercise PR - PIU182

README.md
=> Added sarah to yearbook

README.md
Excited to be part of Codédex! 👩‍💻
=> Final Exercise PR - jordnlnn

README.md
this is my new addition to the README msg for completing this training.
=> Awesome work CodeDex!

README.md
=> Final Exercise PR - Asma Afzal

README.md
I added my name with date and emoji.
=> Added name and date with emoji

README.md
I added my contribution. 👩🏻‍💻🥞
=> Final Exercise PR - coding-pancakes

README.md
=> Final Exercise PR- Mendhonsbertl

README.md
Added my contribution line as part of the final exercise. 🎉
=> Final Exercise PR - bavanaalogan

README.md
This is my contribution to the final exercise :)
=> Final Exercise PR-efan-mc

README.md
=> Final Exercise PR - tfu86

README.md
A comment has been added to the original README.md file.
=> Final Exercise PR - Aryal-Mahesh

README.md
I would like to sincerely thank the creator of this website for providing such a valuable learning resource. It has greatly enhanced my understanding and confidence in using version control.
=> Final Exercise PR - kaung8229

README.md
=> Final Exercise PR - harrakyass here

README.md
Added my name to the code and created a PR to mark the end of the successful code
=> Final Exercise PR - V-E-D-5-here

README.md
=> Final Exercise PR - @Kuria

README.md
Updated the README.md with my name :)
=> Final Exercise PR - Jenn

README.md
=> Add a mem 

README.md
Requesting a PR for the final exercise on GitHub.
=> Final Exercise PR - NessaCarye

README.md
Adding my name for the recordbooks!
=>  "Final Exercise PR - Hughglass"

README.md
=> new info was added

README.md
=> Final Exercise PR - PrabashanaDev

README.md
Added my contribution line to the README! --
=> Final Exercise PR - SYNC-00

README.md
Added introduction line as part of the final exercise.
=> Final Exercise PR - KrioKon12

README.md
Hi, as part of the course instructions, I forked and cloned the repository, then added my contribution (with my name and date). I’ve pushed the changes to my fork and created a PR to merge them into the main branch of your repository. Please review and accept my PR.
=> I contributed to the coddex repository

README.md
added my name, today's date , and an emoji!
=> Final Exercise PR - shahadabn

README.md
=> Final Exercise PR - clivebxby0

README.md
=> Final Exercise PR - nehanXD

README.md
I added my name at the bottom next to the other students
=> i added my name

README.md
=> My contribution!

README.md
=> Final Exercise PR - carlhus-here

README.md
This is the final github exercise.
=> Final Exercise PR - Woodycd

README.md
=> Final Excercse PR - willglad

README.md
=> "Final Exercise PR - shafqat-619

README.md
=> Final Exercise PR - brayanbc22

README.md
=> Final Exercise PR - jalapenotim

README.md
I added my name and some emojis to this thing
=> Final Excercise Pr-JoshuaE92

README.md
=> Final Exercise PR - makenziediaz

README.md
Added my name and date to the yearbook.
=> Final Exercise PR - varma1221
